name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend
        run: |
          cd /home/abdur/server/storage-backend
          git pull origin main
          docker compose up -d --build
